name: linte-test

on: 
  push:

jobs:

  builds:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
      - run: make setup
      - run: make test
      - run: make lint
